### ISSUE TITLE
Compiler error (Init-only setters) when using LangVersion 8.0 in a .NET Standard 2.0 library

### ISSUE THREAD

**Issue by sonnemaf** [Sergio0694/PolySharp#14]
### Description (optional)

I got compiler error CS8400 ```Feature 'init-only setters' is not available in C# 8.0. Please use language version 9.0 or greater.	``` when compiling a .NET Standard 2.0 class library with C# 8.0 as the ```LangVersion```. Upgrading to 9.0 fixed the issue but should not be nesessary.

![image](https://user-images.githubusercontent.com/9335559/198327609-9706a9ae-ad84-4614-adf8-e51fe146f181.png)

### Reproduction Steps

Create a Class Library using the following ```.csproj``` content and this class ```Product.cs```

```xml
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>8.0</LangVersion>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
	  <PackageReference Include="PolySharp" Version="1.6.0" />
	</ItemGroup>
</Project>
```

```cs
using System.Diagnostics.CodeAnalysis;

namespace ClassLibrary19 {
    public class Product {

        [AllowNull]
        public string ProductName { get; set; }
    }
}
```

### Expected Behavior

No compiler error

### Actual Behavior

error CS8400

### System info

This section should contain useful info such as:
- **PolySharp** NuGet version 1.6

### Additional context (optional)

Any additional info that might be useful to resolve the issue.

**Comment by Sergio0694** [comment]
> "Upgrading to 9.0 fixed the issue but should not be nesessary"

Uh... But it is? Init-only setters are explicitly a [C# 9.0 feature](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#init-only-setters) 😅

All that PolySharp does is it adds the necessary types that the compiler checks for in order to enable some language features that do not need runtime support, which is why they can also work downlevel. But each feature is still tied to a language version, so in order to use it you need _both_ the polyfill (which PolySharp generators for you), _and_ a high enough C# language version set in your project. Hope this clarifies things 🙂

**Comment by sonnemaf** [comment]
But the init-only setter is not in my code it is in the generated code.

**Comment by Sergio0694** [comment]
Oooh sorry, I misread the issue. Yeah no this is definitely an issue, I think they're used in one of the polyfills themselves. I'll add a new test project only using C# 7.3 to double check that this doesn't happen. Thank you! 😄

**Comment by sonnemaf** [comment]
Thank you! It is really great to have this. I was using this [Nullable](https://www.nuget.org/packages/Nullable) package before. But PolySharp has much more. Happy!

**Comment by Sergio0694** [comment]
Thank you, really happy to hear it's being useful! 😄
Also just to call out one more advantage of PolySharp: each polyfill is explicitly checked by the generator and it's only generated when it's actually missing. This means you also won't end up with conflicts from other packages nor with duplicate types in case you're multi-targeting and one of the targets you're using does have some of these types defined already 🙂

Also, tip: if you're building a library, you might want to add `PrivateAssets="all"` to the `PackageReference` for PolySharp, so that it'll only be used locally to generate the internal types for you, but it won't be a transitive dependency for your users 😄

**Comment by sonnemaf** [comment]
Thanks for this tip. I will set the PrivateAssets="all".
