### ISSUE TITLE
Polysharp didn't work for me

### ISSUE THREAD

**Issue by goodstas** [Sergio0694/PolySharp#39]
I created Console App for .NET Framework 4.7.2 and added to the project file <LangVersion>11.0</LangVersion>. I installed the PolySharp package .I don't see that it produces some source generators files and i got the exceptions from the compiler.. will be appreciate for advise  what i did wrong. I didn't see the Polysharp in my References list but there is packages.config file and there is a reference there. I attached zip file with a solution. There are 2 projects in solution. Please look on ConsolePolysharp2. Thank you!
[ConsolePolySharp.zip](https://github.com/Sergio0694/PolySharp/files/10416930/ConsolePolySharp.zip)

**Comment by Sergio0694** [comment]
The issue is you're using a legacy-style .csproj project with the `package.config` configuration. This causes the source generators to not run correctly, which is why you're seeing those errors. You need to migrate to an [SDK-style .csproj project](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/overview) 🙂

To clarify: you don't need to change framework or anything, you can keep using .NET Framework 4.7.2 if you want. But you will need to update the .csproj file to use the new format, so that the generators can run.

**Comment by goodstas** [comment]
> The issue is you're using a legacy-style .csproj project with the `package.config` configuration. This causes the source generators to not run correctly, which is why you're seeing those errors. You need to migrate to an [SDK-style .csproj project](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/overview) 🙂
> 
> To clarify: you don't need to change framework or anything, you can keep using .NET Framework 4.7.2 if you want. But you will need to update the .csproj file to use the new format, so that the generators can run.

**Comment by cremor** [comment]
@Sergio0694 This is a very important point since .NET Framework projects are still created with legacy-style .csproj files by Visual Studio. I think this should be mentioned in the readme.

**Comment by Sergio0694** [comment]
Yeah that's a good point, I'll add a warning about this in the readme! 🙂
