### ISSUE TITLE
Support for Inline arrays in C# 12 preview?

### ISSUE THREAD

**Issue by sdcb** [Sergio0694/PolySharp#78]
https://devblogs.microsoft.com/dotnet/new-csharp-12-preview-features/#inline-arrays

**Comment by ds5678** [comment]
Is anyone working on this? I may be willing to do so, but I'm hesitant because I don't have much experience with source generators.

**Comment by Sergio0694** [comment]
This is planned (along with all other new polyfills for C# 12), just waiting for the language to be stable first 🙂
The design of several of the new attribute types has changed over time, so I want them to stabilize before adding polyfills.

**Comment by optiks** [comment]
Hey Sergio, I love your work!

Following on from the C#12 theme, with .NET 8 now released I can’t wait to start using it!

Are you able to share the plans for C#12 support? Is there anything the community can do to help?

Thanks :)

**Comment by eduarddejong** [comment]
Hmm, today I was curious how we can do things by ourselves. So I decided to play around with things myself in order to see how far I can get, and what happened was actually quite interesting.

After setting my csproj TFM to net481 I got several errors, but most obviously that the `InlineArray` attribute was missing.
So I just decided to copy the official InlineArrayAttribute.cs .NET source file into my project.
Which solved that part of the problems.

Another error shown about missing `System.Runtime.InteropServices.MemoryMarshal.CreateSpan` was shown by IntelliSense (but somehow not by the compiler output itself) at that point on my code where I assigned values to my internal array for all the indices.
I was eventually able to remove it by making my own `public static partial class MemoryMarshal` implementation with a `CreateSpan` method and modify that a bit so that it could compile on .NET Framework as well.

However, after these actions, the following more serious compiler error still remained:
```
error CS9171: Target runtime doesn't support inline array types.
```

To me, that suggests that the current situation is that inline arrays are actually impossible on .NET Framework at all, or at least that Roslyn compiler itself does not allow you to do this at least.

So in that case I guess PolySharp alone will not be able to solve it I guess...

**Comment by Sergio0694** [comment]
Oh, I forgot this one. Actually completed by #81.

> "inline arrays are actually impossible on .NET Framework at all"

That is correct, it requires runtime support. This is why it's part of the "runtime supported" attributes which are dummy and don't actually do anything (like eg. `[UnmanagedCallersOnly]`), and are opt-in. They're only meant to make multi-targeted code cleaner.

**Comment by naratteu** [comment]
The [current documentation](https://github.com/Sergio0694/PolySharp/blob/8ed69f93561f0d42aead7a21e4a55307692c133b/README.md) seems to suggest that `[InlineArray]` is supported, but it doesn't appear to be working. What else do I need to add to the code below to make it work?

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>13.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PolySharp" Version="1.15.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

```cs
var arr = new Arr();
System.Console.WriteLine(arr[..].Length);
[System.Runtime.CompilerServices.InlineArray(3)]
struct Arr { char c; }
```

```pwsh
> dotnet run                   
Restore complete (0.3s)
  hello failed with 2 error(s) (0.2s)
    ~/test.cs(3,34): error CS0234: The type or namespace name 'InlineArrayAttribute' does not exist in the namespace 'System.Runtime.CompilerServices' (are you missing an assembly reference?)
    ~/test.cs(3,34): error CS0234: The type or namespace name 'InlineArray' does not exist in the namespace 'System.Runtime.CompilerServices' (are you missing an assembly reference?)

Build failed with 2 error(s) in 1.0s

The build failed. Fix the build errors and run again.
```

**Comment by ds5678** [comment]
`PolySharpIncludeRuntimeSupportedAttributes`

**Comment by naratteu** [comment]
Aha, after adding `-p:PolySharpIncludeRuntimeSupportedAttributes=true`, it only recognizes `[InlineArray(..)]` when inserted directly, rather than using the full name like `[System.Runtime.CompilerServices.InlineArray(..)]`. However, even then, it doesn’t seem like the struct is being transformed the way I expected…

```cs
#:property PolySharpIncludeRuntimeSupportedAttributes=true
#:property PublishAot=false
#:package PolySharp@1.15.0

using System.Runtime.CompilerServices;

System.Span<Arr> arr = new Arr[] { new() };
var barr = System.Runtime.InteropServices.MemoryMarshal.AsBytes(arr);

System.Console.WriteLine(barr.Length);

[InlineArray(3)] struct Arr { char c; }
```

```pwsh
> dotnet run test.cs -f net8 # output: 6
> dotnet run test.cs -f net7 # output: 2
> dotnet run test.cs -f net6 # output: 2
```
